name: Go Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19.x' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Running on Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50

      - name: Test
        run: make test
